In [7]:
import pandas as pd
import glob
import os

In [8]:
path = 'Labelled Data' 
all_files = glob.glob(os.path.join(path, "*.csv"))

# 2. Combine all files into a single DataFrame
# ignore_index=True ensures row numbers are reset and sequential
df = pd.concat((pd.read_csv(f) for f in all_files), ignore_index=True)

# 3. Export to a new CSV file
# index=False prevents row numbers from being saved as a column
# df.to_csv("combined_output.csv", index=False)

In [9]:
df

,score,selftext,subreddit,title,Label,CAT 1
0,1.0,A very minor thing happened which triggered my...,Anxiety,I lost the strength in me,Personality,NaN
1,1.0,"Hi, I am a 52-year-old female who has been dea...",Anxiety,Looking to be supported and support others lik...,Personality,NaN
2,1.0,"I know it’s just the season, it everything so...",Anxiety,I know it’s just the season.,Personality,NaN
3,1.0,I hold a very close connection to my interests...,Anxiety,I hate talking about my interests with people ...,Personality,NaN
4,1.0,Have you ever been triggered just before bed? ...,Anxiety,Anxiety Tonight,Personality,NaN
...,...,...,...,...,...,...
818,1.0,It feels like nobody outside of my family care...,lonely,Disappear,Trauma and Stress,Loneliness
819,1.0,I’ve been dealing with an emotional trauma fro...,lonely,Feeling lonely and left alone,Trauma and Stress,Relationship
820,1.0,I never imagined being a victim of abuse would...,lonely,I never knew how lonely it felt being a victim...,Trauma and Stress,Loneliness
821,1.0,Moved out of my mom's house this year one week...,lonely,First Christmas alone,Trauma and Stress,Loneliness
822,1.0,"I've been neglected, abused, and lonely my ent...",lonely,Never felt so lonely during the holidays,Trauma and Stress,Loneliness

In [10]:
df = df.dropna(how='all')

In [11]:
df

,score,selftext,subreddit,title,Label,CAT 1
0,1.0,A very minor thing happened which triggered my...,Anxiety,I lost the strength in me,Personality,NaN
1,1.0,"Hi, I am a 52-year-old female who has been dea...",Anxiety,Looking to be supported and support others lik...,Personality,NaN
2,1.0,"I know it’s just the season, it everything so...",Anxiety,I know it’s just the season.,Personality,NaN
3,1.0,I hold a very close connection to my interests...,Anxiety,I hate talking about my interests with people ...,Personality,NaN
4,1.0,Have you ever been triggered just before bed? ...,Anxiety,Anxiety Tonight,Personality,NaN
...,...,...,...,...,...,...
818,1.0,It feels like nobody outside of my family care...,lonely,Disappear,Trauma and Stress,Loneliness
819,1.0,I’ve been dealing with an emotional trauma fro...,lonely,Feeling lonely and left alone,Trauma and Stress,Relationship
820,1.0,I never imagined being a victim of abuse would...,lonely,I never knew how lonely it felt being a victim...,Trauma and Stress,Loneliness
821,1.0,Moved out of my mom's house this year one week...,lonely,First Christmas alone,Trauma and Stress,Loneliness
822,1.0,"I've been neglected, abused, and lonely my ent...",lonely,Never felt so lonely during the holidays,Trauma and Stress,Loneliness

In [13]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("kamaruladha/mental-disorders-identification-reddit-nlp")

print("Path to dataset files:", path)

Downloading to /Users/snigdha/.cache/kagglehub/datasets/kamaruladha/mental-disorders-identification-reddit-nlp/2.archive...

100%|██████████| 208M/208M [00:06<00:00, 31.6MB/s]

Extracting files...

Path to dataset files: /Users/snigdha/.cache/kagglehub/datasets/kamaruladha/mental-disorders-identification-reddit-nlp/versions/2